DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, COUNTRY VARCHAR, POPULATION INT);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('San Francisco', 'US', 10000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('서울', 'KR', 20000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('東京', 'JP', 30000);
INSERT INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('부산', 'KR', 40000);
UPDATE CITY SET NAME = '北京', COUNTRY = 'CN', POPULATION = 50000 WHERE NAME = '서울';
DELETE FROM CITY WHERE COUNTRY = 'CN';
INSERT  INTO CITY (NAME, COUNTRY, POPULATION) VALUES ('한국', 'KR', 20000);


-- drop table if exists MEMBER;

-- CREATE TABLE TR_MEMBER(
-- USER_ID VARCHAR(20) NOT NULL,
-- USER_PW VARCHAR(20) NOT NULL,
-- USER_NAME VARCHAR(20),
-- USER_EMAIL VARCHAR(20),
-- USER_PHONE VARCHAR(20),
-- USER_ADDR VARCHAR(20),
-- PRIMARY KEY(USER_ID)
-- );

